// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Friendship struct {
	UserID1 int32
	UserID2 int32
	Status  pgtype.Text
}

type Item struct {
	ID        int32
	OwnerID   int32
	ImageUrl  string
	Category  pgtype.Text
	Color     pgtype.Text
	Style     pgtype.Text
	CreatedAt pgtype.Timestamp
}

type User struct {
	ID        int32
	Username  string
	Email     string
	CreatedAt pgtype.Timestamp
}
